### ISSUE TITLE
Failed at the runas@2.0.0 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by daimob** [josa42/atom-svg-preview#15]
Install failed.

Windows 8.1
Atom 1.0.0

**Comment by lloeki** [comment]
Is this still a thing?

**Comment by daimob** [comment]
Yep, still a thing, even after upgrade to Windows 10.  Any way to get around this?

**Comment by lloeki** [comment]
Can you try to move away the (equivalent of) `~/.atom` directory and start afresh?

**Comment by daimob** [comment]
Re-installed atom - default packages, same issue.

**Comment by daimob** [comment]
Removed the .atom folder, still same error.

**Comment by lloeki** [comment]
Ok, this gives me some baseline. I'll try to get a hand on some Windows license as there's no problem here on OS X and people seem to have a range of similar issues in the Windows world.

**Comment by daimob** [comment]
Great.  This is the full error message:

> runas@2.0.0 install C:\Users\daimob\AppData\Local\Temp\apm-install-dir-115630-8792-bybmfy\node_modules\svg-preview\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\daimob\AppData\Local\Temp\apm-install-dir-115630-8792-bybmfy\node_modules\svg-preview\node_modules\pathwatcher\node_modules\runas>node "C:\Users\daimob\AppData\Local\atom\app-1.0.3\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\daimob\\AppData\\Local\\atom\\app-1.0.3\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\daimob\\AppData\\Local\\atom\\app-1.0.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\daimob\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\daimob\\.atom\\.apmrc" "install" "C:\\Users\\daimob\\AppData\\Local\\Temp\\d-115630-8792-5afcj0\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by mxrachel** [comment]
Still an issue running Windows 10 Professional 64-bit

    Installing “svg-preview@0.6.1” failed.Hide output…

    > runas@2.0.0 install C:\Users\Rachel\AppData\Local\Temp\apm-install-dir-115117-1624-1iten8u\node_modules\svg-preview\node_modules\pathwatcher\node_modules\runas
    > node-gyp rebuild

    C:\Users\Rachel\AppData\Local\Temp\apm-install-dir-115117-1624-1iten8u\node_modules\svg-preview\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\Rachel\AppData\Local\atom\app-1.2.4\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

    gypnpm ERR! Windows_NT 6.2.9200
    npm ERR! argv "C:\\Users\\Rachel\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Rachel\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Rachel\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Rachel\\.atom\\.apmrc" "install" "C:\\Users\\Rachel\\AppData\\Local\\Temp\\d-115117-1624-2egien\\package.tgz" "--target=0.34.0" "--arch=ia32"
    npm ERR! node v0.10.40
    npm ERR! npm  v2.13.3
    npm ERR! code ELIFECYCLE

    npm ERR! runas@2.0.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the runas package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls runas
    npm ERR! There is likely additional logging output above.

**Comment by josa42** [comment]
Is this still an issue with svg-preview@0.7.2. All tests seem to pass on windows now. [=> appveyor](https://ci.appveyor.com/project/josa42/atom-svg-preview/build/3)

**Comment by mxrachel** [comment]
It installs and it is working for me :) Thank you very much! I couldn't get Ctrl+Alt+V to work, but I could toggle it from the menus. It's probably a keybinding problem on my end :).

**Comment by josa42** [comment]
@mxrachel You are right, the keybindings for Windows and Linux were missing. Should be fixed in v0.7.3 (5082a46).
