### ISSUE TITLE
Enabling auto-open crashes Atom.

### ISSUE THREAD

**Issue by lenovouser** [josa42/atom-svg-preview#28]
Title should say everything.

![](http://puu.sh/mXbhg/798f030a8a.png)

**Comment by lenovouser** [comment]
Any updates?

**Comment by josa42** [comment]
I cannot exactly reproduce this. But I hope its fixed in v0.7.4.
Please reopen, if the error still occurs.

**Comment by lenovouser** [comment]
Can confirm that this is not an issue on the latest version anymore. Thanks a lot!
