### ISSUE TITLE
Feature request: export to PNG

### ISSUE THREAD

**Issue by sverweij** [josa42/atom-svg-preview#31]
@josa42 Thanks for cooking & maintaining this useful package! While using it I was looking to export my svg to PNG - but it doesn't seem to be supported yet.

- Would you consider to add _export to png_ as a feature to this package?
- Would you be willing to accept a PR to that effect?    
(I've implemented something similar for atom-mscgen-preview a while ago so I should be able to contribute something working & tested in a reasonable amount of time).

**Comment by sverweij** [comment]
@josa42 - I had some spare time last week and implemented it in a [fork](https://github.com/sverweij/atom-svg-preview/tree/feature/export-to-raster-graphics) (specifically [this commit](https://github.com/sverweij/atom-svg-preview/commit/d3e35a8af7d01843c089cac89a3dae7d8c274440). I've included a sample of the user interaction below. 

- Would you be OK if I made that fork into a PR for this repo?
- The implementation is in CoffeeScript - I noticed the repo has a convert-to-js branch. If you'd rather have the PR in JavaScript (ES6) I'll convert the changes to ES6 as well. 

![export-to-png](https://cloud.githubusercontent.com/assets/4822597/17184960/2d48958e-542f-11e6-99d4-3cde01820c3a.gif)

**Comment by josa42** [comment]
@sverweij Honestly, I don't like to add too many dependencies to the package. You added `svg-to-raster`, which has `phantomjs-prebuilt` as a dependency. That's pretty heavy for a feature, which will probably not be used by most of the users. Why don't you create a separate package for exporting svgs to png?

**Comment by sverweij** [comment]
@josa42 Completely agree on you on the dependencies. However, there's no extra dependencies - the svg to raster module is just 24 lines of code (and that's counting comments) - without dependencies. 

The only change in dependencies is that fs-plus moved from `devDependencies` to `dependencies` - because exporting needs writing to disk...

(PR coming up)

P.S. I _do_ use phantomjs-prebuilt in `mscgenjs-cli` - which you see it in the Save As... dialog in the picture. And that's because there's no other viable alternative. I would move away from it in a pinch even there...

**Comment by josa42** [comment]
@sverweij Oh sorry, mis read your code. I thought you where using this: [svg-to-png](https://github.com/filamentgroup/svg-to-png). 😆
