### ISSUE TITLE
Close Preview Pane Automatically

### ISSUE THREAD

**Issue by mikebronner** [josa42/atom-svg-preview#44]
Love this package! Unfortunately it doesn't close the split pane that it created when automatically showing the preview.

If automatically hide preview and split pane settings are enabled, could it also close the preview pane, so that my editor pane expands back to the full width?

Thanks! :)

Atom 1.12.9
svg-preview 0.11.0

**Comment by josa42** [comment]
You will get that be behavior, if you turn "Remove Empty Panes" (`core.destroyEmptyPanes`) in the Core Settings on.

I don't think this package should override this, as some (like me) would like to keep the pane open.
