### ISSUE TITLE
export to png/jpg doesn't work

### ISSUE THREAD

**Issue by nergdron** [josa42/atom-svg-preview#45]
When using this package in Atom on Windows, the live preview works, but the export to png/jpeg in the right click menu does nothing. It doesn't report any errors, it just doesn't create a file.

**Comment by sverweij** [comment]
@nergdron what version of windows and what version of atom were  you on when you encountered the issue? Do you encounter it with every svg or with some? 

(I tried to reproduce the issue on a windows 7 machine with atom 1.12.9 with [this svg from wikipedia](https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg) but wasn't able to)

**Comment by nergdron** [comment]
Just tested at work, works fine on Ubuntu 16.10. Retrying on my home machine (windows 10 x64), can't repro with that tiger image either. It also zooms correctly, per the other bug I reported, so it must be something specific to the SVG I was working with. I'll try to create a minimum repro case for both tonight.
