### ISSUE TITLE
zoom doesn't work

### ISSUE THREAD

**Issue by nergdron** [josa42/atom-svg-preview#46]
When attempting to zoom in on a drawing in the preview pane, it fails to zoom in or out. It appears to just be changing the displayed viewport of the SVG, and not the size at which it's rendered, so it just moves the SVG around and adjusts clipping.

**Comment by nergdron** [comment]
Strange. After updating to Atom 1.13.0, this problem has disappeared. So it may have just been some interaction with the previous version on my system.

**Comment by XVicarious** [comment]
I want to chime in and say on Atom 1.15.0, and svg-preview 0.11.0 zoom is doing what you said it was doing.
