### ISSUE TITLE
No preview with Atom 1.25.0

### ISSUE THREAD

**Issue by ingorichter** [josa42/atom-svg-preview#54]
Preview of SVG doesn't work with 1.25.0 of Atom

**Comment by swrobel** [comment]
Same issue here, although to be specific, it doesn't appear automatically if I have it set to open automatically, it won't do so for Current or Right panes. It will if I set the pane to Bottom. It will show regardless of the pane I have it set to if I use the keyboard shortcut.

Atom 1.25.0
macOS 10.13.3

**Comment by DavidOD** [comment]
same issue here with Atom 1.26.1. I can not see preview window at all.

**Comment by SKalt** [comment]
As of atom 1.31.x, svg-preview 0.12.1, I can't reproduce this issue.
