### ISSUE TITLE
I want to take this over

### ISSUE THREAD

**Issue by uyouthe** [josa42/atom-svg-preview#62]
Hello.

I'm an active user of this package and its health is crucial to me. Right now I'm going to focus on existing issues but I already have a shortlist of new features I want to introduce. I want to turn this into high-quality open-source product and make it to at least Product of the Day on Product Hunt.

If you want to discuss this, feel free to contact me.

**Comment by twifty** [comment]
@uyouthe Have you taken published a newer version? I would consider switching providing you fix some of the annoyances.

**Comment by uyouthe** [comment]
Since 2019 I gave up on Atom, so this issue should be closed I guess.
